run:
  timeout: 2m

linters:
  enable-all: false
  disable-all: true
  fast: false
  enable:
    - errcheck          # проверяет обработку ошибок
    - goimports         # автоматически исправляет импорты
    - govet             # стандартные проверки компилятора
    - gosimple          # упрощение сложного кода
    - staticcheck       # продвинутые статические проверки
    - unused            # находит неиспользуемые переменные и импортированные пакеты
    - typecheck         # расширенная проверка типов
    - misspell          # ищет опечатки в комментариях и строках
    - unparam           # удаляет ненужные параметры функций
    - gocyclo           # вычисляет цикломатическую сложность методов
    - gocognit          # измеряет когнитивную сложность метода
    - bodyclose         # предупреждает о возможных утечках ресурсов
    - gosec             # находит потенциальные уязвимости безопасности
    - nolintlint        # проверяет правильность использования комментариев nolint
    - prealloc          # рекомендует предварительное выделение памяти
    - rowserrcheck      # проверяет правильную обработку ошибок sql.Rows
    - paralleltest      # находит параллельные тесты
    - revive            # альтернатива vet
    - stylecheck        # проверяет соблюдение стиля написания кода
    - goconst           # находит часто используемые константы и подсказывает создание новых
    - gofmt             # автоматическое форматирование
    - godox             # генерирует документацию Godoc
    - dogsled           # проверяет читаемость вложенных if-выражений
    - makezero          # показывает возможные проблемы с инициализацией нулевых значений
    - nestif            # заменяет множественные вложенные условия

linters-settings:
  gocyclo:
    min-complexity: 20
  misspell:
    locale: en_Us.UTF-8
  goimports:
    local-prefixes: github.com/mycompany
  whitespaces:
    strict: true
  nestif:
    depth: 3
